srcdir: /opt/pipeline/bin

path:
  bowtie2: /opt/microconda/bin/bowtie2
  star: /opt/microconda/bin/STAR
  samtools: /opt/microconda/bin/samtools
  bedtools: /opt/microconda/bin/bedtools
  featureCounts: /opt/microconda/bin/featureCounts
  rnaseqc: /bin/rnaseqc
  blast2bam: /bin/blast2bam
  rnaseqmut: /bin/rnaseqmut
  umicollapse: /bin/umicollapse.jar
  cpup: /bin/cpup

barcode:
  barcode3_r1: AGATCGGAAGAGCACACGTCTG
  barcode3_r2: AGATCGGAAGAGCGTCGTGT
  # remove (primer 5->3) on begin of R1, `-g`
  # remove (primer 5->3) on begin of R2, `-g`
  RT_primer_F: ACACGACGCTCTTCCGATCT
  # remove (primer 3->5) on end of R1, `-a`
  RT_primer_R: AGATCGGAAGAGCGTCGTGT

# other default setting
workdir: results
tmpdir: /tmp
