#!/usr/bin/env bash

dataconf=$1
jobs=48
if [[ $# -gt 1 ]]; then
    jobs=$2
fi
FLASK_ENV=development snakemake -j ${jobs} -q --rerun-incomplete -s /opt/sacseq/Snakefile --configfiles /opt/sacseq/config.yaml ${dataconf}
