#!/usr/bin/env bash

dataconf=$1
jobs=48
if [[ $# -gt 1 ]]; then
    jobs=$2
fi
snakemake -j ${jobs} -p --rerun-incomplete -s /opt/sacseq/Snakefile --configfiles /opt/sacseq/config.yaml ${dataconf} -p
