remote_theme: just-the-docs/just-the-docs@eadddd7afde8e01da41fe06a9ee69d25aad8280e
ga_tracking: G-EFHY8WFMHK
ga_tracking_anonymize_ip: true

callouts:
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red
